column_mapping:
  categorical_features:
  - job_title
  - industry
  - occupation
  numerical_features:
  - age
  
data_format:
  header: true
  separator: ','
service:
  calculation_period_sec: 10
  min_reference_size: 30
  monitors:
  - data_drift
  moving_reference: false
  reference_path: reference_df.csv
  use_reference: true
  window_size: 30